[build] improve maintenance scripts for launchpad
Enable running scripts from any folder.

diff --git a/launchpad-export b/launchpad-export
--- a/launchpad-export
+++ b/launchpad-export
@@ -5,13 +5,11 @@
 
 LP_EXPORT_FILE=launchpad-upload.tar.gz
 LP_EXPORT_DIR=launchpad-temp
-SCRIPT=./launchpad-export
 
-if [ "$0" != "$SCRIPT" ]
-then
-	echo "Script must be run from Parlatype root folder – quitting now."
+cd `dirname "$0"` || {
+	echo "Error: Could not change to script dir"
 	exit 1
-fi
+}
 
 mkdir $LP_EXPORT_DIR 2>&- || {
 	echo "Remove folder $LP_EXPORT_DIR first – quitting now."	
diff --git a/launchpad-import b/launchpad-import
--- a/launchpad-import
+++ b/launchpad-import
@@ -5,18 +5,16 @@
 
 IMPORT_FILE=launchpad-export.tar.gz
 TEMP_DIR=launchpad-temp
-SCRIPT=./launchpad-import
 
 echo "Maintenance script to import translations from Launchpad."
 echo "Download from https://translations.launchpad.net/parlatype/trunk/+export"
 echo "and save as $IMPORT_FILE into this folder."
 echo
 
-if [ "$0" != "$SCRIPT" ]
-then
-	echo "Script must be run from Parlatype root folder – quitting now."
+cd `dirname "$0"` || {
+	echo "Error: Could not change to script dir"
 	exit 1
-fi
+}
 
 # Test for import file
 if [ ! -e "$IMPORT_FILE" ]
